Replace post autoload dump script with command
There is an issue caused by upgrade to psr/log 3.*
which changed its interfaces and added extra types.
The composer/composer library used by ComposerScripts
has its own logger interface which is not compatible
with psr/log 3.*.

If composer's interface gets loaded and then any
psr/log 3.* gets loaded, it causes this error:

  ERROR: Declaration of Psr\Log\AbstractLogger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = [])

In our case it was the Sentry library that triggered
this error by initializing NullLogger, but in general
it could have been any class that was being instantiated
while executing any of the post autoload dump commands.

Since there isn't a nice solution how to avoid this and
Composer isn't going to update the interfaces any time
soon (see https://github.com/composer/composer/issues/11246),
we cannot try to initialize Console application at this
point and we just simply need to execute the command
in a separate process.

remp/crm#3050