Fix initialization of google charts library
Error:

   ```
   TypeError: google.visualization is undefined
   ```

For some reason this graph stopped working when new google charts URL
is used (changed by commit 1e45c2c9f1ad6f9cd12a40a06656cee0288a618f).

To reinitalize / load google graph's package, we check if
`google.visualization` is not undefined.

remp/crm#1066