Fix errors (missing getTime) in GoogleBarGraph
Graph in widget ActualSubscribersRegistrationSourceStatsWidget stopped
working because of these issues.

Errors:

   ```
   TypeError: dateRange.min.getTime is not a function
   TypeError: dateRange.max.getTime is not a function
   ```

Reason: Google charts' function `getColumnRange()` can return null. Or
it returns datetime in string format instead of Date (so no getTime()
function).

Fix will ensure we have proper Date object in min and max dateRanges.

remp/crm#1066