Nette v3.0 - Pre-set filesystems when ApplicationMountManager created
Missing parent constructor caused error when Nette container was initialized.

```
InvalidArgumentException: League\Flysystem\MountManager::mountFilesystem
expects argument #1 to be a string.
in /var/www/html/vendor/league/flysystem/src/MountManager.php:76
```

remp/crm#1979